---
title: Mental Conditioning
author: Kurt R. Peters
date: '2020-09-20'
slug: mental-conditioning
categories:
  - Musings
tags: []
---


- Conditioning
	- Conditioning—becoming conditioned—requires training. Repeated exposure to ingrain behavioral responses, to reduce the cognitive effort requires to enact the desired response; to achieve automaticity or, in this context, skill.
	- This is obvious within the context of physical conditioning—we take for granted that achieving a desired state of physical conditioning requires training.
	- But this same language applies equally to mental, not just physical, health: analogous to a well-conditioned body, a well-conditioned mind is one that is healthy, resilient, highly skilled/tuned, and this—to complete the analogy—just as obviously requires training to achieve.
	- (Within psychology, the idea of mental conditioning goes back at least to Pavlov, Skinner and the other behaviorists who discovered “classical” and other forms of conditioning, which amount to methods by which responses can be trained to follow (previously unassociated) stimuli. The application of mental conditioning to treat mental illness was advanced later with Beck’s Cognitive Behavioral Therapy (CBT), which is one of the few forms of psychotherapy that has been empirically demonstrated to be effective. The downside is that it requires a lot of training and maintenance work to be successful. But this is no different from any other type of training.)
	- So what does a well conditioned mind look like?
		- ///
	- And what type of training is required to achieve this state?
		- For one thing: Know your goals. Develop a clear vision of the person you want to be, the qualities of mind you want to possess.
			- A major goal for my mental conditioning: Not manufacturing meaning; understanding that most things are not serious but evanescent, even random and without deeper significance—in short, accepting events philosophically; abiding. Giving fucks only when truly deserved.
			- Treating everything as equally serious is not only inefficient and exhausting, it leaves you open to manipulation/exploitation by (malevolent or just emotionally needy) bad actors, who will take advantage of your total investment of self in all causes to effectively take control of you.
			- ///this might be a separate deep dive on manufacturing meaning…
				- Why manufacture meaning? because it is dissonance reduction: if what I’m doing isn’t meaningful, then why am I doing it? (paired with the belief that I should only be doing meaningful things, i.e., a high-meaning self-concept)
				- The other trap I fall into is the natural justice fallacy—believing that justice exists independently of humans, and that therefore some expectation of basic fairness in the order of events is to be had. Paired with my dispositional abhorrence of injustice, this belief sets me up to explode because, in reality, there is no natural justice — the world is neither fair nor unfair, it simply unfolds — and having no control over these events, my emotional health is left at the mercy of external, essentially random events.
		- Then: Work at it. Just like physical training, it will start out feeling awkward, demanding, extremely effortful, even exhausting. But repeated training will over time condition your mind, reducing the effort requires to activate responses/reactions, creating a new baseline self, and upgraded “you” from which to continue building and improving. Just as a second year of physical training builds upon the baseline level of conditioning developed during the first year.
