---
title: White Knuckling through Life
author: Kurt R. Peters
date: '2020-09-20'
slug: white-knuckling-through-life
categories:
  - Musings
tags: []
---


- White-knuckling through life
	- I am a repentant white-knuckler. That’s always been my approach to life: if something is challenging, I double down and try to bull through it. Fundamentally I don’t believe any situation can get the better of me unless I let it. This is obviously swell from a self-efficacy perspective, but it becomes maladaptive when applied to every challenge. This is when adaptive grit turns into pathological perseverance. Sound familiar? I’m not going to argue that white-knuckling is bad across the board — grit is pretty clearly an effective trait for succeeding in life; instead, I want to think more deeply about where to draw the line, so that all you other white-knucklers can understand that sometimes it’s ok to say “it’s not me, it’s this situation” without feeling like a failure, and in particular how to turn these stressful-to-the-point-of-intolerable situations into opportunities for personal improvement. Life is too short not to be enjoyed.
	- ///
		- All we have is our fucking time. The question is — the only question is — who gets it? Who or what *deserves* your life? *Everything else flows out of the answer to that question.* Risk assessment, contingency planning, budgeting, all those “rational adult” considerations are just tools to help you figure out how to get what you want; they can’t tell you what to want in the first place. And so it’s not childish/immature to let your passion drive everything else. This is the essential truth the philosopher David Hume captured when he wrote that “reason is and ought only to be the slave of the passions” (///confirm phrasing). If you don’t decide where you want your hours and days to be spent — what object is deserving of the only resource that matters to you, and the only resource you actually have unilateral control over — someone else will. This is sadly the outcome for most of us, I imagine — we are born into a cultural factory line, with life stages and milestones pre-defined, and we allow ourselves to be rolled along the conveyor belt until one day we realize that we’ve ended up somewhere we never really wanted to be — perhaps even *despite* thinking we were behaving like rational, disciplined, mature adults. The problem is that rationality and discipline are just tools we can use to achieve our goals, and no one can evade the responsibility of identifying their own goals, making their own decisions about where to invest their life. That has to come first.
			- https://gmb.io/time/
		- Productivity is not a substitute for fulfillment. It can pass in the short term but over the long term — if you develop expertise in areas that were never very meaningful to you — the feeling of executing and being productive is no longer sufficient to mask the lack of meaning. It’s not enough to be good at something; to be fulfilling, it needs to be something you actually care about. This is not as farfetched as it sounds, given the conveyor belt of life most Western professionals find themselves on.
	- ————————————
	- So sometimes shit gets real. Life gets so stressful that maintaining equanimity becomes impossible. I can bounce back from a bad day, but there have been stretches of my life when the stressful days string together, become *cumulative*, and acting like a functional human being begins to feel unsustainable. This is when my default strategy of white-knuckling my way through challenges becomes totally debilitating.
	- Red flags:
		- You realize, in moments of self-reflection, that you are turning into someone you don't want to be -- even if it's considered normatively appropriate/adaptive for the situation. The critical thing to understand here is that normative expectations (e.g., how an effective leader behaves in your organization) aren’t necessarily right, and disagreeing with them is absolutely valid.
		- You realize your primary motivation for powering through is simply to end the stress you are experiencing — not to achieve some other, more positive goal or to deliver some outcome/product to someone else.
		- Less acutely: you realize that you are just constantly grinding — the average stress level may be relatively low, but it has settled into a constant background; every day is just about getting to the next; there is no internal motivation, no active pursuit of personally meaningful goals
		- Physical symptoms: chest pain, illness, poor recovery, poor sleep
		- Collateral damage: homelife, other relationships start to suffer
	- In these situations, you have to choose a coping strategy. How you cope with significant stressors is a function of many things (like all human behavior) but it has a huge impact on your quality of life, and more so as the scope of the stressor increases. A non-exhaustive list:
		- Resilience: The canonically “adaptive” coping strategy: you remain engaged with the situation, avoid getting emotionally shut down, and actively seek solutions to the challenge. Some people are more resilient than others; this can be taught (mental conditioning; role models can help) but there is also a strong personality component.
		- Reframing: Reinterpreting the situation — seeing every challenge as an opportunity; seeking out failure as a chance to grow/improve. This has been shown to actually lower the negative physiological impacts of acute stressors. But there are obviously limits.
		- Abiding: This is the foundation of Stoic philosophy: care only about what you can control, and abide the passage of all other events with equanimity. Sort of like a less negative form of apathy (again, no risk no reward).
		- Grit: Powering through on sheer force of will (aka white-knuckling); this can look impressive to others but it will prove debilitating if it becomes the chronic coping strategy.
		- Apathy: A temporary solution and ultimately maladaptive, since emotionally disconnecting from the world is like wrapping yourself in scar tissue — protective but also constraining: No risk, no reward.
		- Exit: Removing yourself from the situation. Choosing a radical break, amounting to a life change.
	- This is all feedback, and certainly people vary not only in their disposition to certain strategies, bust also to which strategies they fall back on in certain situations. One not unreasonable summary of a person’s life is the series of such challenges faced and their responses to them. In fact, it’s an illuminating exercise to draw this list up for yourself: the milestone challenges you’ve faced through your life and how you coped with it. It’s a simplification, but like any trendline it might reveal an arc to your life that you weren’t aware of living in the day-to-day weeds. Unless you’re one of the lucky “resilients,” you might realize that you have a pattern of dysfunctional coping.
	- One of the things you learn as you get older is that some situations are just not ok. There is no amount of reframing that will spin them into a positive light; they are just objectively — by the standards of “reasonable” people — untenable. In these situations it’s ok, finally, to say “It’s not me, it’s you.” After a little bit of experience with life, it’s ok to accept that you aren’t going to push yourself to change, to adapt yourself to this unfair situation, but to reject the demands of the situation upon you as untenable. For those of us who habitually power through challenges, this requires absolute honesty with yourself, because it initially feels like admitting failure. It feels like weakness. But the only failure is in not living life consciously, not actively pursuing your own quality of life — however you define it.
	- The question at that point is whether you have the courage to break out of the situation, to introduce a discontinuity into your timeline. Because the normative, socially appropriate expectation is that people do not just say “fuck it” and break out of a challenging situation. People don’t like quitters. But that’s not we’re talking about here. What we are talking about are those situations that are somewhere between the reasonable, to-be-expected obstacles we all face as humans trying to make our way in society, and the truly traumatic situations that, in an ideal world, no one would ever be exposed to (live combat, sexual abuse, etc.). I’m talking about are situations most people will experience a handful of times during their lives. The big forks in the road. And what I’m trying to argue is that when facing these choices, the number one consideration should be self-care. It’s not selfishness (///link to MDA on self-care != selfish?). Because at the end of the day it’s all about quality of life, and if you remain in a situation that is actively damaging your quality of life, rather than choosing to break away from it — however radical that action may appear to others — you are sacrificing not just your present happiness but your potential happiness, and that will limit your ability to support others now and in the future. Obviously you don’t want to put at risk the welfare of those who already depend on you, but at some point the situation becomes so profoundly damaging that continuing will significantly impair your ability to provide for them. *Radical breaks are always a risk, more so when you have dependents, but that shouldn’t categorically prevent you from considering such breaks as a viable possibility.*
	- So ultimately — and everyone’s threshold for this ultimatum will differ — it boils down to a question of courage: status quo or radical change? Resign to suffering or reach for happiness? It’s not really a question, of course — we should reject any stigma being attached to the choice to improve one’s quality of life. As a rule, we should *all* be pursuing a state of thriving. The question is whether you have the gall to do it when you need to. To stand up for yourself.
	- This is the Exit strategy I mentioned above. The trick here is that to make Exit work, it shouldn’t be defensive but offensive. That is to say, you should be using the chance to make a lifechange *toward* a new desired state more than you are running *away* from the untentable situation. 
	- Decision tree: Hell yes vs. no
		- ///Credit to GMB
		- Is this too simplistic? For day-to-day decisions obviously yes. But for these big, life-forking decisions, it’s appropriate. All we have is our time on this earth and we should consciously, actively choose how we spend it, most especially when it comes to decisions that direct huge chunks of that finite resource. 
		- The answer is to unapologetically live life on your own terms. To fight for *your* goals — not someone else’s goals, but  your own image of a meaningful, fulfilling life. No one — *no one* — has a rightful claim on your pursuit of personal fulfillment.
			- Step 1: Know what you want
				- Critically: don’t settle for society’s/anyone else’s conception of certain goals (e.g., if you want to be a fitness consultant, don’t assume it has to involve X, Y, and Z — don’t censor yourself. What does your ideal job look like *to you*?)
				- ///what is is that I want? describe my ideal job…
					- Speaking at conferences
					- Teaching local classes
					- Personal training/coaching
					- Owning or sharing a custom gym space
					- Designing my own methodology for personal improvement/wellness >> “Like a fox” this is more than just physical fitness
			- Step 2: Pursue it without apology
			
