---
title: 'Science Corner: Training '
author: Kurt R. Peters
date: '2020-09-20'
slug: science-corner-training
categories:
  - Fitness
tags: []
---

- Science Corner
	- Warming up
		- What changes occur in the body as it transitions from “cold” to “warmed up”?
		- Capillary expansion/blood flow/oxygenation? >> esp. in relation to muscle tissue?
		- Synovial fluid? esp. in the spine
		- Hormones
		- Joints/tendons: can these get “warm”?
		- Glycogen release? (hepatic glycogen?) Ketones? TGs?
	- Impact of exercise on vascular health
		- You know this already right? Exercise is good for your circulatory system. That’s why they call it “cardio”. But it’s actually more interesting than that — and in a way that underscores the importance of movement and resistance training above and beyond pure cardio.
		- Proposed mechanism: shear stress on vascular system (due to actual physical act of placing blood vessels under mechanical stress, i.e., movement and resistance training, not just “getting the blood flowing”) up-regulates markers of vascular health, in particular the vasodilator NO
		- So improving cardiovascular health is not just about “getting the blood flowing” but actually moving your blood vessels (which are, of course, part of the muscles that are being moved).
		- In fact, there is evidence that even static stretching has positive effects on vascular health for the same reason (stretching the blood vessels)
	- What is optimal cool down?
		- What changes occur in the body in the first hour post-workout?
		- ///analogous questions to warm-up
		- What is the goal of a cool down? Theoretically to promote recovery and decrease risk of injury
		- So: what happens in the body during recovery? When does recovery shade into atrophy following exercise-induced stress? How long is the plateau between the two?
			- In particular: what happens to physiologically during sleep in terms of recovery from a workout?
	- How long does it take to replenish muscle glycogen?
		- How does this change in the context of LCHF diet?
		- What role does hepatic glycogen store play in fueling resistance training? How much glycogen (in terms of duration of a typical workout) can be stored/deployed in this way?
		- How long does it take to burn glycogen? (e.g., how much does a 3s planche hold burn?)
			- Details of intracellular metabolism of muscle cells under high-resistance activity: when does (and how long does it take to) switch from aerobic to anaerobic? Does metabolic flexibility (being fat-adapted) significantly affect this?
	- Blood pooling & skeletal muscle assistance in circulation
		- Why is blood pooling bad?
		- What is body’s mechanism for preventing it?
		- What can you do to promote this process? (basically: need to activate the relevant muscles occasionally, i.e., not stay in a single position for long periods of time)
	- Does “active recovery” actually promote recovery? If so, what are the mechanisms?
		- Does it help with DOMS?
		- If there are mechanisms… how can the be exploited to recommend an optimal AR strategy? What would an example session look like? (duration, intensity, exercise types)
	- Why does stress interfere with a workout?
		- At a physiological/mechanistic level: what are the hormones involved and why do they impair force production?
		- e.g., does cortisol somehow inhibit muscle fiber activation/efficiency?
	- Importance of minerals to LCHF training, and generally in relation to muscle fiber activation:
		- Magnesium (and relation to cramping)
		- Calcium (role in muscle tissue at cellular level)
		- Potassium
		- Sodium (cf. Art & Science of Low Carb Performance recommendation)
		- Caffeine (what is this actually doing within muscle fiber cells?)
	- Foam rolling
		- And other mechanical self-administerable interventions to promote recovery, including:
			- voodoo floss
			- massage
			- nerve gliding/flossing
		- In particular: what this the theory behind the mechanism of these interventions? myofascial release? breaking up scar tissue adhesion? what are these interventions actually doing under the skin?
	- Occlusion
	  - What is the definition of occlusion training? What is the physiological effect? What is the practical benefit? How to incorporate it? (e.g., is this part of the effect achieved through straight-arm and isometric training?)
	- Cramping
		- No solid evidence for traditional theories (dehydration, electrolytes)
		- One theory is that cramping is due to fatigued muscle fibers, which are susceptible to abnormal increases in activity of muscle fibers and decreased activity in GTOs (Aetiology of skeletal muscle 'cramps' during exercise: a novel hypothesis.
		Schwellnus MP <https://www.ncbi.nlm.nih.gov/pubmed/?term=Schwellnus%20MP%5BAuthor%5D&cauthor=true&cauthor_uid=9232553>1, Derman EW <https://www.ncbi.nlm.nih.gov/pubmed/?term=Derman%20EW%5BAuthor%5D&cauthor=true&cauthor_uid=9232553>, Noakes TD <https://www.ncbi.nlm.nih.gov/pubmed/?term=Noakes%20TD%5BAuthor%5D&cauthor=true&cauthor_uid=9232553>.)
			- The inverse stretch reflex corroborates this theory: stretching the muscle alleviates cramping by activating the GTOs, which inhibit muscle fiber activity
	- Effects of nutrient timing on athletic performance on a LCHF diet
		- My basic question is: does spiking insulin (by ingesting carbs and/or protein) prior to workout suppress fat metabolism during workout? and if so, does this matter for resistance style (high intensity/anaerobic) workouts, which are primarily fueled by glycogen anyway?
		- I guess a related question is: even at the most fat-adapted, metabolically flexible state, can you actually get to the point where high-intensity strength training burns fat rather than glycogen? Or is any meaningful volume of resistance training going to require glycogen for fuel?
		- Where do ketones factor into this? Can they benefit resistance training?
	- Metabolic flexibility
		- Overview of three metabolic systems: 
			- phosphogenic, glycolytic, aerobic
			- traditional breakdown of conditions under which each is active
		- What is ideal in terms of GST?
			- Fat-burning for as long as possible, given hard cap on length of time/intensity phosphogentic and glycolytic systems can support activity?
			- Importance of aerobic conditioning for GST: (cf. Low’s comments about the Chinese gymnastics program) — cardio may not directly transfer to improved gymnastics skill but it does increase the foundation of fitness, allowing the metabolic system to be more efficient; which in turn improves training quality
		- Link to Attia’s self-experiment on increasing his metabolic flexibility during cycling
