---
title: A Thought Experiment
author: Kurt R. Peters
date: '2020-06-28'
slug: a-thought-experiment
categories:
  - BodyLanguage
tags:
  - intro
---

This series is an exploration of a simple thought experiment: 

*What if you regarded your body as a separate -- even alien -- organism, but one capable of communicating, learning, and adapting?*

* How would you talk to this organism? 
* How would you listen to what it’s saying? 
* How could you try to teach it new things? 

Communicating, learning, and adapting are the essential hallmarks of what we call cognition, and the purpose of this thought experiment is to reorient your relationship to your body so that you view it not as a puppet whose strings you can pull at will (our default way of relating to our bodies), but as an independent organism with a mind of its own, one which communicates and learns in ways very different from how we typically think of “communicating” and “learning.”

Without understanding the different languages the body uses to communicate, attempts at training the body can be painfully inefficient, if not simply painful. Imagine trying to teach someone a movement as complicated as the clean and jerk by just saying one word over and over. It simply isn’t going to be effective: Your method of communicating is woefully inadequate for shaping such a complex behavior. 

Of course, coaches and trainers have developed more effective techniques for teaching bodies how to perform complex movements, but this knowledge is scattered and not easily accessible to the average athlete, especially non-professionals. Understanding the various languages your body uses to communicate will demystify this knowledge and give you the tools to efficiently train your body.
